### ISSUE TITLE
What is the rationale for SetValue in addition to FunctionalRange?

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#101]
SetValue provides similar computation functionality to FunctionalRange. What is the rationale for this? 

This design seems to blend (a) the calculation of ranges with (b) the application of ranges to change models. Additionally, its not clear to me what the computation in SetValue enables that can't be achieved with FunctionalRange. As a result, there seems to be some unnecessary redundancy which adds complexity and breaks abstractions. 

It seems to me that SetValue could be simplified to simply use a range (and `listOfParameters`, `listOfVariables` and `math` could be eliminated). What could be achieved with SetValue computations could instead be achieved with FunctionalRange. This would further separate the application of ranges to change models from the calculation of ranges.

**Comment by matthiaskoenig** [comment]
This is a very good point! I completely agree with this. We should do this.

**Comment by fbergmann** [comment]
the core thing that `SetValue` adds over the functional range, is to specify the target to assign the value of the computation to. Other constructs do not change model values. usually the expression just assigns the value of another range to the specified target, but we left the constructs, as we already had them on other elements, and would be implemented already. 

I dont quite see how to just drop it.

**Comment by matthiaskoenig** [comment]
The idea is to just drop the calculation on SetValue. All calculations can be done in the functionalRange and then just the range be used in the SetValue. This would remove duplication and make implementation easier. Also from a data point of view this is much cleaner because all arrays which are required for setValue can be calculated at the initialization of the RepeatedTask. 
Yes, we need SetValue and the target in there. We just don't need a duplicated calculation.

**Comment by fbergmann** [comment]
I don't see the advantage. Especially, since SetValue just inherited those attributes from ComputeChange. It will require more time updating the implementations, and targeting different versions.

**Comment by luciansmith** [comment]
My understanding is that it's FunctionalRange that could be dropped, not SetValue.  I think FunctionalRange was originally conceived as a 'while' loop (instead of a 'for' loop), but didn't end up becoming that in the end, and ended up with identical functionality.  If we dropped something (for L2!) I think I would drop FR over SV.

**Comment by jonrkarr** [comment]
Based on this conversation, it sounds like there's some divergence in the interpretation of `SetValue` that needs to be pinned down before we can evaluate whether the function of `SetValue` and `FunctionalRange` is redundant and can potentially be simplified.

My interpretation is `FunctionalRange`s should be calculated **before**  the individual iterations. In contrast, I think  `SetValue` is intended to be calculated **during** each iteration. This means that `SetValue` can accumulate change for previous iterations (depending on the value of the reset attributes), which is not true for `FunctionalRange`. This would mean that `SetValue` must be kept and `FunctionalRange` could be eliminated.

Alternatively, if it were understood that `FunctionalRange` should be executed **during** each iteration, set value computations could be dropped in favor of separating the calculation of new values and applying them to models. This would mean that implementations have to separately determine the lengths of functional ranges from their child ranges and calculate their values.

**Comment by jonrkarr** [comment]
It was decided to continue to support both even though they have overlapping functionality.
