### ISSUE TITLE
Disallow data generators for outputs of specific subtasks of repeated tasks

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#107]
*Note, this is a proposal to not add a fairly obvious feature.*

Presently, there is no mechanism to record the results of one or more specific subtasks of a repeated task. The whole task has to be recorded. If a simulation experiment involves several subtasks, and only the result of the last task is needed, there is no mechanism to get the results for just this subtask.

This could be addressed by (a) adding an id attribute to `SubTask` and (b) allowing data generators to reference subtasks.

I bring this up because its an obvious feature to want. However, the results of an individual subtask can be easily obtained in post-processing. Because repeated tasks produce multi-dimensional output that have to be stored in a format such as HDF5, this is easy to do with the formats that would be used to store such results. Because they can be obtained in post-processing, SED support for addressing outputs of specific subtasks is not essential. As a result, to avoid increasing the complexity of SED, I  suggest such a feature not be added to SED.

**Comment by matthiaskoenig** [comment]
The results of the subtasks are concatenated (as stated in the specification) so that it becomes impossible/difficult to resolve the subtasks afterwards. So your proposed solution does not work easily.

Importantly only subtasks which could be concatenated can occur together as subtasks. 
To execute multiple subtask which cannot be concatenated this have to be split in two repeated tasks with the same ranges.

**Comment by jonrkarr** [comment]
As I wrote in the first line, this is a note to discourage something like this is from creeping into SED-ML.

**Comment by jonrkarr** [comment]
For simplicity, it was decided not to be able to reference this from variables of data generators. 

A future version of SED-ML should have the capability to access specific slices of the results of repeated tasks.

**Comment by luciansmith** [comment]
It turns out we basically already had this restriction in the spec, but I went ahead and made it more explicit by adding the last sentence of the following paragraph:

"The target attribute may also be used to reference an entity within the SED-ML file itself, by containing
a fragment identifier consisting of a hash character (#) followed by the SId of the targeted element. As
of SED-ML Level 1 Version 4 this may only be used to refer to a DataSource in a Variable or to refer to
ranges within a repeatedTask (see Listing 2.46). No other SED-ML element has mathematical meaning
that can be obtained by using its id as the target of a Variable."
