### ISSUE TITLE
Modify or remove the setting of symbols (via SetValue)

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#108]
The `symbol` attribute of `SetValue` intended to enable repeated tasks to set the value of the internal state of simulation tools.

There are multiple issues with this
- There are no examples for this. 
- I suspect the usage is minimal as well.
- There are already other more primitive mechanisms to set the properties of a simulation
   - In particular, `initialTime` of `UniformTimeCourse` also sets the value of the one recognized symbol, `time`.
   - Other properties can be set with algorithm parameters. These could be set in repeated tasks in a more general way as proposed in #98.
- Because there are already other mechanisms that could be used to implement this, the need for a separate mechanism for symbols is not obvious to me and the existence of another mechanism complicates SED-ML and the implementation of SED-ML.
- If its desired to have a distinct mechanism to set symbols separate from the setting of algorithm parameters, this should be supported at a more primitive level so that it can also be used in conjunction with instances of `Task` rather than introducing this capability at the more abstract level of repeated tasks.

**Comment by matthiaskoenig** [comment]
This is used to set `amount`, `concentration` or `particle number` for species. This is a clear currently existing use case for the symbol. I have many examples for this which I could not encode so far in SED-ML until we add the `amount` or `concentration` symbol (which was basically decided). Not sure how to do this otherwise.

The setValue is not for algorithm parameters.

**Comment by jonrkarr** [comment]
I hope we can clarify the semantics of this as part of the revision of repeated tasks. Part of the problem is that tools are using repeated tasks quite differently and SED-ML doesn't yet capture enough information for a document to indicate what the intended interpretation is.

**Comment by luciansmith** [comment]
@jonrkarr , have you found an example of a repeated task that is interpreted differently in two tools, in this context?  (Or more generally, any SED-ML file that is interpreted different ways in different tools.)

**Comment by jonrkarr** [comment]
There's divergence in a variety of places
- Interpretation of master location in COMBINE file
- Locations where generated files are saved especially when COMBINE archives have multiple SED-ML files (e.g., tellurium vs others)
- Resolution of XPaths -- some tools can recognize XPATHs that don't exist to round trip issues with their own export. This is different from what Lucian asks, but introduces confusion by creating the expectation that invalid XPAths can work with other tools.
- Different interpretation of internal URI fragments (e.g., VCell, tellurium)
- Ignoring KISAO terms for algorithms without warning
- End to end (tellurium) vs independent subtasks. Different interpretation of where variable values for SetValue come from.

**Comment by luciansmith** [comment]
To clarify that symbols are almost always used to *read* values out of a model rather than being used to *set* values, I added the following to the 'Symbols' section:

"With very few exceptions, symbols refer to mathematics of a model that can be read out of the model,
but cannot be set directly. You cannot use a symbol attribute to set the time of a model, for example,
nor may you set the Stoichiometry matrix nor the elasticities. The only partial exception to this is that
the amount, concentation, or particle number of a species may be set by an element using both a target
attribute to indicate the species and a symbol to indicate which form to use."

**Comment by jonrkarr** [comment]
This makes sense. Since symbols, by definition, don't appear in model descriptions, there should be no way to set them as part of a description of a changed model.
