### ISSUE TITLE
Clarification needed what min and max mean with scale="log10" on axis

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#130]
When setting the `min` and `max` in combination with `scale="log10"` on an axis object the interpretation is ambiguous.
Is the min and max the min and max of the log data or the original data. 

One has a linear axis
```
<xAxis type="linear" min="0.1" max="10" grid="true" style="style_axis"/>
```
Now one wants the axis in log10 scale with the same min and max. Two possibilities exist:

**A**
```
<xAxis type="log10" min="0.1" max="10" grid="true" style="style_axis"/>
```
or 

**B**
```
<xAxis type="log10" min="-1" max="1" grid="true" style="style_axis"/>
```
i.e. the exponent of the log10. 
The variant **B** is what matplotlib does, i.e. the min and max are on the scale of the respective axis.
A clarification sentence is required.

**Comment by luciansmith** [comment]
I think the units of min and max should be the same as the units of the data.  The log10 should only affect whether the axis has the same amount of space between 1 and 2 as 2 and 3, or the same amount of space between 1 and 10 as 10 and 100.  (The labels should reflect this, too--the tics should say '1', '10', '100', evenly spaced, instead of actually converting them to log values.)

If matplotlib doesn't do this, that sounds like a bug in matplotlib, frankly, or at least a very poor design choice.

I agree that we should clarify in the spec.

**Comment by luciansmith** [comment]
Added the following text:

"Note that min and max will have the same units as the data plotted along it, regardless of the value of the
type. An axis with a min value of \1" and a max value of \100" will either be plotted with ’50’ halfway
between those two extremes if the type is \linear", or with ’10’ halfway between those two extremes if
the type is \log10"."
