### ISSUE TITLE
Add 'reverse' attribute to axis.

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#131]
The following should be the expected behavior but must be clarified in the specification:

> Limits may be passed in reverse order to flip the direction of the axis. For example, suppose ``y`` represents depth of the ocean in m. The y-axis limits might be set like the following so 5000 m depth is at the bottom of the plot and the surface, 0 m, is at the top.
```
<yAxis min="5000" max="0"/>
```

**Comment by agarny** [comment]
If we are to follow [Lucian's view](https://github.com/SED-ML/sed-ml/issues/130#issuecomment-809666495) (with which I agree), then we probably ought to have something like:
```xml
<yAxis min="0" max="5000" revert="true"/>
```
In other words, `min` and `max` should refer to the data.

**Comment by luciansmith** [comment]
I don't quite follow your argument, @agarny . I think Matthias is suggesting that 'min' for a y axis should mean 'the value at the bottom of the graph' and 'max' should mean 'the value at the top of the graph'.  If 'min'>'max', that's not illegal; rather, it just suggests that the polarity of the graph be reversed.

I'm not sure this is actually a good idea, unless it turns out to be simple to implement for everyone.  If not, I would just say we should introduce a validation rule that min<max.

(Also, can I assume that you meant 'reverse' and not 'revert' in your example?)

**Comment by agarny** [comment]
First, yes, `reverse` and not `revert`.

Second, I meant that if the computed data is to have a value in the range [0; 5000] (and not [5000; 0]), but that for some reasons we want it displayed on a Y axis that goes from 5000 (at the bottom of the axis) to 0 (at the top of the axis), then I would probably use something like:
```xml
<yAxis min="0" max="5000" reverse="true"/>
```
because, as you said [here](https://github.com/SED-ML/sed-ml/issues/130#issuecomment-809666495), `min` and `max` should refer to the minimum/maximum value for the data.

It's like a linear vs. a log10 scale, you want:
```xml
<xAxis type="log10" min="0.1" max="10" grid="true" style="style_axis"/>
```
and not:
```xml
<xAxis type="log10" min="-1" max="1" grid="true" style="style_axis"/>
```
i.e. your data is in the range [0.1; 10], not [-1; 1].

Hopefully, I have made myself a bit clearer. :)

**Comment by matthiaskoenig** [comment]
Here some example do show the reversed order and the log scales. I went with the data range for the log10 in my implementation.
![axis](https://user-images.githubusercontent.com/900538/112906181-08d83200-90ec-11eb-8d01-850fc6232b26.png)
All the same data, just different axis in all for plots.

```
 <listOfOutputs>
    <plot2D id="plot0" name="No axes" legend="true">
      <listOfCurves>
        <curve id="curve0" name="S1" logX="false" style="style_curve" xDataReference="dg_time" logY="false" yDataReference="dg_S1" type="points"/>
      </listOfCurves>
    </plot2D>
    <plot2D id="plot1" name="Axis (reversed order and grid)" legend="true">
      <xAxis type="linear" min="10" max="0" grid="true" style="style_axis"/>
      <yAxis type="linear" min="10" max="0" grid="true" style="style_axis"/>
      <listOfCurves>
        <curve id="curve1" name="S1" logX="false" style="style_curve" xDataReference="dg_time" logY="false" yDataReference="dg_S1" type="points"/>
      </listOfCurves>
    </plot2D>
    <plot2D id="plot2" name="Axis (log axis and style)" legend="true">
      <xAxis type="log10" min="0.1" max="10" grid="true" style="style_axis_blue"/>
      <yAxis type="log10" grid="true" style="style_axis_red"/>
      <listOfCurves>
        <curve id="curve2" name="S1" logX="false" style="style_curve" xDataReference="dg_time" logY="false" yDataReference="dg_S1" type="points"/>
      </listOfCurves>
    </plot2D>
    <plot2D id="plot3" name="Axis (hidden, no legend, min/max)" legend="false">
      <xAxis type="linear" style="style_axis_none" min="2" max="8"/>
      <yAxis type="linear" style="style_axis_none" min="0" max="8"/>
      <listOfCurves>
        <curve id="curve3" name="S1" logX="false" style="style_curve" xDataReference="dg_time" logY="false" yDataReference="dg_S1" type="points"/>
      </listOfCurves>
    </plot2D>
    <figure id="figure1" numRows="2" numCols="2">
        <listOfSubPlots>
            <subPlot plot="plot0" row="1" col="1"></subPlot>
            <subPlot plot="plot1" row="1" col="2"></subPlot>
            <subPlot plot="plot2" row="2" col="1"></subPlot>
            <subPlot plot="plot3" row="2" col="2"></subPlot>
        </listOfSubPlots>
    </figure>
  </listOfOutputs>
  <listOfStyles>
    <style id="style_curve">
      <line style="solid" color="#000000" thickness="2"/>
      <marker style="square" fill="#000000" size="6"/>
    </style>
    <style id="style_axis">
      <line style="solid" color="#000000"/>
    </style>
    <style id="style_axis_blue">
      <line style="solid" color="#0000FF" thickness="2"/>
    </style>
    <style id="style_axis_red">
      <line style="solid" color="#FF0000" thickness="4"/>
    </style>
    <style id="style_axis_none">
      <line style="none"/>
    </style>
  </listOfStyles>
```

**Comment by luciansmith** [comment]
According to https://docs.google.com/document/d/1PgZ9bVZHhUYzxKcpZROmx4qaNDpYdyvRJpVBktOJdKA/edit we decided to add a 'reverse' attribute to the Axis to handle this situation.  

Here's my description:

"The reverse attribute indicates whether the axis should be plotted from the minimum value to the
maximum value (\false") or from the maximum value to the minimum value (\true") (i.e. left to right
or bottom to top, depending on the axis). If not defined, either is technically possible, but should be
assumed to go from minimum to maximum."

**Comment by luciansmith** [comment]
Somehow, a 'reverse' attribute ended up on the UML of an AbstractCurve, with no explanation in the text.  I'm removing it, but if anyone remembers why it was there, let me know.

**Comment by matthiaskoenig** [comment]
I am pretty sure this is just some left-over from the `reverse` attribute on axis.
