### ISSUE TITLE
Add optional attribute `symbol` to Change and SetValue

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#141]
To be able to set model changes and task changes in `amount` or `concentration` on SBML species the `symbol` is needed on `Change` and `SetValue`. Currently the Change and SetValue only specify the `target` xpath, but does not allow to set the symbol which would be required to specify what is set in the model.
Solution: Introduce the optional attribute `symbol` on Change and SetValue.

E.g. 
Set amount or concentration of species (instead of the urns the KISAO would be used):
```
<model language="urn:sedml:language:sbml" [..]>
  <listOfChanges>
    <changeAttribute target="/sbml:sbml/sbml:model/sbml:listOfSpecies/species[@id='S1']" symbol="urn:sedml:symbol:amount" newValue="1.0"/>
    <changeAttribute target="/sbml:sbml/sbml:model/sbml:listOfSpecies/species[@id='S2']" symbol="urn:sedml:symbol:concentration" newValue="10.0"/>
  </listOfChanges>
</model>
```

Same issue for SetValue
```
<listOfChanges>
  <setValue target="/s:sbml/s:model/s:listOfSpecies/s:species[@id=’S1’]" symbol="urn:sedml:symbol:amount" range="current" modelReference="model1">
      <math xmlns="http://www.w3.org/1998/Math/MathML">
     ...
     </math>
  </setValue>
</listOfChanges>
```
edit: issue clarified and clearer title

**Comment by fbergmann** [comment]
i would definitely allow it. Not sure about requiring it though. Currently it does get resolved based on the sbml model elements hasOnlySubstanceUnits and compartment SpatialDimensions. But since one of the design goals was to make this work with SBML and CellML, i dont think we can require it.

**Comment by matthiaskoenig** [comment]
Sorry, was my formulation. Yes this should be an optional attribute. It is just required if one wants to set amount/concentration contrary to the `hasOnlySubstanceUnits` ;)

**Comment by luciansmith** [comment]
Having looked into this, I disagree that the meaning of ChangeAttribute should change based on an additional 'symbol'.  ChangeAttribute is an XML format-based change, and the meaning of the attribute is set in the model specification language.  I don't think SED-ML can possibly change it.  For SBML species, it's still possible to set the initial amount or concentration, simply by setting the 'initialAmount' or 'initialConcentration' attributes.  (If need be, you could use SED-ML to delete one and set the other, even.)  

The 'hasOnlySubstanceUnits' attribute doesn't actually have anything to do with the intial amount or concentration.  Rather, it defines how the symbol should be interpreted in other contexts in the model.

For better or worse, SED-ML has two modes:  in its first mode, it is an XML manipulation language.  In its second mode, it is a model semantics manipulation language.  'changeAttribute' is, in my view, the first of the two, while 'computeChange' is the second.  The XPath of a changeAttribute is supposed to point to an attribute, which your examples do not--instead, they point to the element itself.  To accomplish what you want, I would use:

    <changeAttribute target="/sbml:sbml/sbml:model/sbml:listOfSpecies/species[@id='S1'/initialAmount]" newValue="1.0"/>

if the model had an initialConcentration set, you'd need to additionally clear that:

    <changeAttribute target="/sbml:sbml/sbml:model/sbml:listOfSpecies/species[@id='S1'/initialConcentration]" newValue=""/>

but I don't think mixing semantic manipulation into the XML manipulation here is wise or coherent.

(For SED-ML L2, I think we should drop XML manipulation entirely, and make it simpler to do semantic manipulation.  But that's a different discussion.)

**Comment by matthiaskoenig** [comment]
@Lucian What you suggest will work for the first Subtask, i.e. initial changes on a model at the beginning of a simulation. But changes to the model state later on such as in a second Subtask cannot be achieved via `initialAmount` or `initialConcentration`. As I understand SBML, the initialAmount and initialConcentration attribute are only evaluated at the loading of the model/and changes of the first subtask.

**Comment by luciansmith** [comment]
This is true!  In that case, a ChangeAttribute element is the wrong choice, since it can only change the attributes, which, as noted, only apply at the beginning of the simulation.  You would want the ComputeChange construct instead, as that can be used to set the current value of an element of a model.

**Comment by luciansmith** [comment]
This is now incorporated into the spec, but I feel like we should resolve the disagreement between Matthias and I before closing the issue.  Does anyone else have an opinion?

My thought is that we should reserve the 'ChangeAttribute' class to change actual XML attributes in a model.  For a species, this would mean the initialConcentration or initialAmount attributes.

Matthias (and correct me if I'm wrong!) would like to use a 'ChangeAttribute' to change the *current value* of the species in the model *state*.  I assume he would like to do this because it is approximately 5000 times simpler to create the XML for this than it is to create the XML for a ComputeChange, where you have to muck about with several children and use MathML just to set a simple double. 

I sympathize with this position, but in my opinion, 'fixing how to change the model' is something that will simply require a redesign with SED-ML level 2, at which point I could easily imagine a ChangeValue along the lines of:
```
<changeValue model="model1" target="S1" value="3.2" valueType="concentration"/>
```
But this is not the SED-ML we are working with at this time, sadly, and I think the ChangeAttribute element is the wrong tool to use to shanghai it into doing something it's not designed to do.

**Comment by matthiaskoenig** [comment]
Hi Lucian,
I am working the next few days on the remaining SED-ML issues on my side. As part of this I will test this issue and if the current solution works for me. I am pretty sure the ComputeChange and SetValue will cover all my use cases.
I will update this issue.

**Comment by luciansmith** [comment]
Sounds perfect!

**Comment by fbergmann** [comment]
> I sympathize with this position, but in my opinion, 'fixing how to change the model' is something that will simply require a redesign with SED-ML level 2, at which point I could easily imagine a ChangeValue along the lines of...

Yes, lets stock for the change subclasses, to currently only do raw XML maniplulations for L1V4.

**Comment by luciansmith** [comment]
Just as a wrinkle:  @jonrkarr is using 'changeAttribute' for non-XML languages, which makes it seem a little churlish to not allow it for XML-based languages, too.  In defense of keeping it the way it is, though, they are also not using XPaths, so we could say 'if you use XPath, you must point to an actual attribute'.

**Comment by jonrkarr** [comment]
Yes, change attribute should be allowed for non-XML. In such cases, targets should be resolvable addresses. Model language should be responsible for defining targets for their language. I don't think SED-ML needs to try to dictate how model languages should handle this.

> you must point to an actual attribute

I hesitate to say this because some languages e.g., Smoldyn and BNGL don't have objects an attributes quite like XML. I suggest leaving this up to model languages.

**Comment by fbergmann** [comment]
I agree with the current resolution

* added symbol for setValue
* sticking to explicitly calling out the xpath target to the attribute to change in ChangeAttribute. Using a symbol there would lead to conflicts and would no longer allow raw xml manipulations irrespective of the modeling language. 

Since we introduced `TargetType` so that non-xml languages can specify what should be changed by ChangeAttribute, they could easily have formulations in there that would address specifically which aspect of an element should be changed. Since we dont go into detail describing it here, we dont need to introduce another attribute there.
