### ISSUE TITLE
How should data generators with invalid targets be handled when sub-tasks of a data generator involve multiple models?

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#151]
## Example
Consider this scenario
- A repeated task has multiple sub-tasks
- These sub-tasks involve multiple models
- Some data generators for the repeated task have targets that are not valid for all models

## How this creates a challenge for simulation tools to provide good error message
I think the above should be considered valid. But, its hard for software implementations to provide good error messages in the above scenario without more information. 
- Data generators have references to tasks
- In this case, a repeated tasks indirectly references multiple models
- In this scenario, the model scope of each target of each data generator is not well-defined
- For basic tasks (`sed:task`), simulation tools can raise errors when a target for a data generator is not valid for the associated model. Simulation tools can't do this for sub-tasks of repeated tasks because the target could be intended to match a different model referenced by a different subtask. The best a simulation tool could do is raise an error if a target is not defined for any model referenced by the subtasks of a repeated task.

## Why this can't resolved with the current version of SED-ML
I don't see a good way to capture more information given the current structure:
- References from data generators to models could be used to provide more information, but multiple model references would be needed for a data generator to apply to multiple models. 
- References from data generators to subtasks (that are basic tasks) would also capture more information, but not allow capturing data from multiple sub-tasks.

## Proposal
To help simulation tools provide better errors to users, it would be helpful to add attribute to `sed:dataGenerator` which allows references to multiple models (for use with repeated tasks). This would give simulation tools enough information to know which variables are expected to be produced for each subtask.

**Comment by luciansmith** [comment]
I feel like in L2, the job of constructing output should be moved to the tasks, which would solve this whole thing.

Anyway:  for now, assuming repeated tasks produce multidimensional output, would it be possible for a DataGenerator referencing a particular model's target to pull out the relevant data and drop the dimensions that don't contain the target?

**Comment by jonrkarr** [comment]
Yes, that's possible. Targets that aren't defined for a particular subtask could generate a matrix of `NaN`. This is what BioSimulators is currently doing. However, one implication of this is that its more difficult to validate targets, meaning its easier for users to not know they're making mistakes. Put it another way, other ways of describing outputs that should be generated could be more conducive to generating helpful error messages for users.

**Comment by luciansmith** [comment]
Instead of generating a matrix of NaN, what if that dimension simply wasn't included?

**Comment by jonrkarr** [comment]
I think NaN is the best way to achieve something like this while embracing matrices as a data structure for results. Biosimulators works this way.

**Comment by luciansmith** [comment]
Looking into this in more detail:

I think Variables should always point to a single target in a single model.  As such, if it has a taskReference that involves multiple models, I think we should add a validation rule that it must also contain a modelReference.

As such, if a particular SubTask does not modify a given model, the Variable will remain at the same value over the course of that SubTask.  (This could actually be useful if the Math of the DataGenerator involved Variables from multiple models.)

Allowing a Variable to point to two different models that happen to both have an element with the same ID seems really fragile, and I don't like it very much.

**Comment by jonrkarr** [comment]
Yes, task references aren't quite enough to enable good validation.

For backward compatibility, model references could remain encouraged, but optional. When present, model references would enable stricter (and I think more informative) validation.

Actually, I think such model references would need to be optional in the current scheme. Otherwise, repeated tasks would become limited to a single model because (a) data generators must be attached to top-level tasks (rather than subtasks) and (b) data generators would become limited to individual models.

**Comment by luciansmith** [comment]
> Actually, I think such model references would need to be optional in the current scheme.

I don't believe this is correct.  Individual Variable elements would be required to point to specific models, but a different Variable could point to a different model, in either the same DataGenerator or in a different one.

The new validation rule I would add would be to say (in the Variable section):

"If the taskReference is a RepeatedTask that involves multiple models, the modelReference must be defined, and must point to one of those models."

This would still allow a different DataGenerator to point to elements of the other models, so wouldn't restrict functionality at all.

**Comment by jonrkarr** [comment]
I think I understand what you're suggesting now:

- Variables of data generators also specify model references
- When variables of data generators have (a) a task reference to a repeated task and (b) a model reference, their value is only defined for subtasks that use involve that model. In a matrix representation of the value of the variable, the slices that correspond to other subtasks of the repeated task would have value NaN.

This would allow the same validation of targets of variables of data generators which is currently possible with basic tasks.

If a repeated task involved two models and model references were used, their results would need to be piped to different data generators.

**Comment by luciansmith** [comment]
I continue to not like NaNs in this context.  Here's how I see the situation:

I imagine the collective model state of any Task to be the initialized version of every Model in the document.  Any given Task may change those initialized values for exactly one of the Models.  Any RepeatedTask uses Tasks to change the initialized values of one or more of the Models from this same pool of Models.  While an individual SubTask is changing one Model, the remaining Models keep their state, whatever that might be (initialized or changed).

As such, a modeler might want to simulate one Model, then use the results to initialize another Model with a SetValue between SubTasks, say, mod2.S1 = mod1.J0.  Then, while simulating mod2, they might then want to output the change in S1 by collecting 'mod2.S1 - mod1.J0' in a DataGenerator.  This wouldn't work if mod1.J0 was set to be 'NaN' just because that SubTask was targeting mod2 and not mod1 at the time.

**Comment by jonrkarr** [comment]
I think what we can take away from these threads is that the semantics of repeated tasks are not sufficiently clear, and that this is important to resolve for consistency. I like pseudo code as a mechanism to more precisely communicate the intended order. Pseudocode wouldn't need to imply that a specific algorithm is required; any mathematically equivalent algorithm could be used.

I don't follow several of the above
- Tasks don't change models, only iterations of repeated tasks do
- Subtasks don't directly change models; but their child repeated tasks can
- All SetValue changes have to be applied before any subtask is executed. There's no way to indicate that a SetValue should be run between a specific set of subtasks. The way to achieve something similar is to have subtasks whose tasks are instances of Repeated Task with SetValue children
- Mapping results from one model to another can be done with SetValue. I don't see where data generators come in.

**Comment by luciansmith** [comment]
I probably could have been much clearer.

a) Tasks change one model each.  Repeated Tasks, by dint of potentially executing several Tasks, may change several models, with each model change effected by a single Task (via a SubTask).
b) I don't understand this--a RepeatedTask has a child SubTask, not the other way around?
c) There is now a way to apply a SetValue between SubTasks, because we gave SubTask a child ListOfChanges.  Hence, it is now possible for one SubTask to run, and then subtask2's child SetValues execute, based on the new model state.
d) I was particularly unclear with this bit:  I was talking about two different things.  First, a SetValue child of a SubTask that set mod2.S1 to be equal to mod1.J0.  Then I imagined a separate DataGenerator that pointed to the RepeatedTask, with two Variables (mod1.J0 and mod2.S1), whose Math child was 'mod2.S1 - mod1.J0':

task1:  simulate steadystate on mod1
task2:  simulate uniform on mod2
task3: repeat once:
      a) task1
      b) task2, but first set mod2.S1 = mod1.J0

DataGenerators:
    S1change = mod2.S1 - mod1.J0 (in task3)

Ouputs:
   report: S1change

**Comment by luciansmith** [comment]
Fixed some text regarding this issue and added the mentioned validation rule.

I think some pseudocode in an appendix is indeed probably the right way to further clarify the semantics here, though I'm also open to more wording fixes if anyone wants to propose anything.

**Comment by luciansmith** [comment]
OK, I put in a potentially controversial solution, so the editors should probably vote on it.

Basically, I first claim that a Variable retains its value over the course of a Simulation that doesn't involve its model.

Then I say that if you want to get rid of that dimension, you just give that object RemainingDimension children that don't include the irrelevant Task:

In the DataGenerator bit:

"Output from multiple models
It is possible to create a RepeatedTask that affects multiple models through different SubTask children.
In this situation, individual Variable children of a DataGenerator must define both a taskReference to
the RepeatedTask and modelReference so it’s clear which specific element is being tracked. However,
the question then becomes: what value does that Variable take while the RepeatedTask is performing a
Simulation in a SubTask that does not involve that Model? In this situation, the Variable is assumed
to retain its last known value for the duration of the Simulation (which will be its initialized value if no
Simulation has been performed yet that affects that Variable).

If those unchanging dimensions are not relevant to the desired output, it is possible to reduce the
dimensionality by adding RemainingDimension children, and only adding the ids of the Task elements
that involve the Model the Variable points to."


In RemainingDimension:
In the second case, the Variable is multidimensional, but some of those dimensions involve a Task that
does not reference the Model from which the Variable is drawn. In these cases, if the Variable is given
RemainingDimension children for the tasks that change the relevant Model, but not the ones that do
not, the resulting data will not include the dimension where the Variable’s Model was not involved.

**Comment by luciansmith** [comment]
Add some examples before voting.

**Comment by luciansmith** [comment]
I've created an example and moved the discussion to the wider community (hopefully) by posting on sed-ml-discuss:

https://groups.google.com/g/sed-ml-discuss/c/VgzM_Q8121Q

**Comment by nickerso** [comment]
> I've created an example and moved the discussion to the wider community (hopefully) by posting on sed-ml-discuss:
> 
> https://groups.google.com/g/sed-ml-discuss/c/VgzM_Q8121Q

@agarny and I have gone through this one and as per the above thread, we believe that option 3 is the expected results for that given example. If the orders of the sub-tasks were the same, we think the results would then be option 1.

Adding the model reference is a good thing. As is having more examples and demonstrations. At this point I think rather than trying to refine the spec any further it makes more sense to demonstrate the expected behaviour via examples and/or pseudocode and leave the spec refinement to L2 - where we think a more rigourous definition of the repeated tasks would actually make it clear that option 2 would be the expected behaviour.

**Comment by luciansmith** [comment]
Update:  At the SED-ML Editor's Meeting, we decided that we should just recommend that people not use a RepeatedTask that references multiple models; it's just too confusing.  https://github.com/SED-ML/sed-ml/commit/d835543cb8820d05a4108f03dcad10223d048fa4 adds this to the spec.

**Comment by fbergmann** [comment]
this formulation works for me
