### ISSUE TITLE
Clarify use of anyURI vs URN for model languages and data formats

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#181]
2.1.1.8 says model languages and data formats should be specified by anyURIs. Should these have type URN?

**Comment by luciansmith** [comment]
Looking things up, it looks like the answer is no--URI is the generic term, and while we do constrain ourselves to the 'urn:...' format for some things (like the 'language' attribute') we don't use that constraint for other things.  We could theoretically explicitly limit the language attribute specifically to URNs, but since we're actually *more* constrained than that, I don't think we need to have a new 'URN' type.

**Comment by luciansmith** [comment]
https://danielmiessler.com/study/difference-between-uri-url/

**Comment by jonrkarr** [comment]
Consistent values of these attributes is important for portability of SED-ML among tools. Because URNs are a special case of URIs (a regular expression pattern), this additional constraint is noted in the text. The schema could also reflect this additional constraint. This would in turn clarify the UML diagrams (which are derived from the schema) and help programs that interpret the schema validate documents.

**Comment by luciansmith** [comment]
Done!  I hadn't quite understood the request originally; I assumed you wanted anyURI replaced wholesale with URN.  It's now required to be a URN for model/language and dataDescription/format.
