### ISSUE TITLE
Why is newValue in ChangeAttribute of data type string?

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#38]
I just wondered why the `newValue` in class `ChangeAttribute` is of type `string`.
Should this not be data type `double`?

**Comment by luciansmith** [comment]
The short answer is 'because it's XML, and everything is a string in XML'.  You can have attributes in XML that are further restricted to be doubles, etc., but all of them will at least be strings.

It is possible for ChangeAttribute to target a non-double attribute in a file for any number of reasons: you may want to change a species to be a boundary species, for example, or visa versa, exchanging the strings 'true' and 'false'.  The way it's described now, you can make any change you like; if we changed it to 'double', it would be much more restrictive.

**Comment by matthiaskoenig** [comment]
Thanks for explanation. This is solved.
