### ISSUE TITLE
Clarifications needed on how to plot data from repeatedTasks

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sed-ml#58]
# Issue
Currently it is unclear how to plot data from repeatedTasks.
For instance one of the specification examples

> This example produces three dimensional results (time, species concentration, multiple repeats).  SED-ML \currentLV does not include a way to post-process these values, so it is left to the implementation on how to display them. One example would be to flatten the values by overlaying them onto the desired plot.

It must be clarified how to handle data from repeatedTasks in plots.

**Comment by fbergmann** [comment]
agreed ... for l1v4 it would be nice if there would be a whole set of rules that would sort this out

**Comment by luciansmith** [comment]
When I went to go plot results from repeated tasks in SED-ML I ran into no problems at all.  The repeats just all end up on the same plot (if 2D) or down the 'repeat' axis if 3D.  Is there anything more complicated that needs to be said?

**Comment by luciansmith** [comment]
OK, this is now clarified:

Added this to the xDataReference for AbstractCurve:

"The dimensionality of the xDataReference must match the y data, but need not be one-dimensional.
When a curve is being displayed, each one-dimensional vector within the x and y data should be displayed
on the same plot. This will effectively flatten the data to the two dimensions of the plot. When being
displayed as lines, each vector should be plotted separately, so that the plot is not overlaid with spurious
lines from the end of one vector to the beginning of the next."

And this to the x/y/zDataReference of a Surface:

"As with an AbstractCurve, the dimensionality of the xDataReference, yDataReference and zDataReference
must match each other, but need not be one-dimensional. When a surface is being displayed, each onedimensional vector within the x, y, and z data should be displayed on the same plot. This will effectively
flatten the data to the three dimensions of the plot. When the data is being plotted as lines, Each vector
should be plotted with its own line, so that the plot is not overlaid with spurious lines from the end of
one vector to the beginning of the next."

**Comment by luciansmith** [comment]
Oh, I also changed the example text, since we *do* provide a way to reduce the dimensionality of the data:

"SED-ML Level 1 Version 4 provides ways to post-process these values with the DependentVariable
class, but here they are not used, meaning that every individual element in the xDataReference is plotted
vs. every individual element in the yDataReference, effectively flattening the values by overlaying them
onto the desired plot. The breaks between dimensions should be used as breaks between any connected
lines, so that spurious lines from the end of one plot to the beginning of the next are not present."
