### ISSUE TITLE
Add note to specifications that KiSAO terms be referenced by KISAO: rather than KISAO_

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#81]
SED-ML uses a variant of KiSAO ids with `:` instead of `_`. This can cause confusion. The specifications should include a note about this.

**Comment by matthiaskoenig** [comment]
Yes, this must be updated in the specification. I will take care of this.

**Comment by luciansmith** [comment]
@matthiaskoenig I couldn't find any change you put in, so I put in my own.  After the description of the format of the kisaoID:

"Note that the
use of a colon predates KiSAO’s switch to using an underscore in official KiSAO URLs. We continue to
use the colon here for backwards compatibility, and because a kisaoID is not a URL."
