### ISSUE TITLE
`name` attributes should be removed from tables 2.10, 2.11 of L1V3 specs because change elements don't have names

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#85]

**Comment by luciansmith** [comment]
What specification are you looking at?  There is no table 2.10 in the l1v4 draft spec.

**Comment by jonrkarr** [comment]
L1V3.

**Comment by luciansmith** [comment]
Ah, OK.  Then yes, these changes have already been done, because the tables were removed entirely.  There were other problems that were even more serious than these in other tables/figures, so they've all been scrapped and replaced.

https://github.com/SED-ML/sed-ml/blob/master/specification/level-1-version-4/sed-ml-L1V4.pdf

**Comment by matthiaskoenig** [comment]
Closing this. Has been resolved in L1V4 draft spec.
