### ISSUE TITLE
Replace resolution of "MIRIAM URNs" with resolution of modelXchange ids

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#86]
Following the conversation in #79, I suggest modelXchange be embraced rather than Identifiers.org (MIRIAM). This is more readily implementable than resolving identifiers.org ids. Also, identifiers.org presently only encompasses a few namespaces for models.

This would also address the problem raised in #78.

**Comment by luciansmith** [comment]
My understanding was that identifiers.org could be expanded to encompass anything.  Can it be extended to modelXchange?

(Also, would this be an L1v4 or L2 suggestion?)

**Comment by jonrkarr** [comment]
For L1V4, I think this should be clarified that MIRIAM is now identifiers.org. I think its also important for the specs to point out that support for this is very limited among simulation tools, in practice limited to just a single identifier.org namespace.

Presumably the EBI will add modelXchange to identifiers.org. This could be part of L2.

**Comment by luciansmith** [comment]
I've gotten a bit lost in the series of proposals to this end.  There are currently several references to 'miriam' in the text, most of which are references to particular biomodels, i.e. 'urn:miriam:biomodels.db:BIOMD0000000048'.

Are we changing these?  And if so, to what?  Should we just have actual URLs to particular Biomodels files, given that biomodels has changed their naming scheme, and blindly hoping that 'BIOMD000000xxxx_url.xml' no longer works consistently?

**Comment by jonrkarr** [comment]
I think general support for MIRIAM ids has to go. Its impossible to implement this. There's no scheme to resolve MIRIAM ids to model files. 

For backward compatibility, I think BioModels ids could remain as the special singular case of MIRIAM ids. Personally, I don't love this because the COMBINE archive philosophy is to keep everything local. I'd prefer to encourage one practice.

modelXchange doesn't exist yet, so that's not an option.

**Comment by luciansmith** [comment]
I didn't end up mentioning identifiers.org at all, but instead just changed all the miriam URNs to straight URLs.

New text reads:

MIRIAM URNs are no longer recommended due to increased difficulty in resolving them, but the scheme
is still valid and interpreters may find SED-ML files that use them. An example for the definition of a
model via an URI is given in Listing 2.30. The example defines one model m1 with the model source
available from urn:miriam:biomodels.db:BIOMD0000000012. The MIRIAM URN can be resolved into
the SBML model stored in BioModels Database under the identifier BIOMD0000000012 by querying the
Biomodels webservice and requesting the ‘main’ SBML file for that biomodel. The resulting URL is
https://www.ebi.ac.uk/biomodels/model/download/BIOMD0000000012?filename=BIOMD0000000012_url.
xml.

I think this is straightforward enough to close the issue, but I'm more than happy to make further changes to wording if need be, or to add something new about identifiers.org.

**Comment by jonrkarr** [comment]
Seems good. I think this removes the expectation that simulation tools support this and suggests this feature may be removed entirely in a future version.

Agreed identifiers.org isn't helpful to mention. The successor to MIRIAM doesn't provide a path to resolve model files either.

**Comment by matthiaskoenig** [comment]
I agree. Remove all miriam examples and use direct urls (https://...) to the model files for now. State that miriam urn are not recommended any more.
