### ISSUE TITLE
XPATHs for sbml:parameter are not consistent throughout the L1V3 specifications

### ISSUE THREAD

**Issue by jonrkarr** [SED-ML/sed-ml#88]
One particular source of confusion about target XPATHs are the examples that involve `sbml:parameter`. Although `sbml:parameter` does have a `value` attribute, this is not employed consistently throughout the examples. Some example use it. Some examples omit `/@value` and treat this as an implicit part of the XPATH.

**Comment by luciansmith** [comment]
The examples are consistent:  the only time @value is used is for 'changeAttribute'.  For everything else, you are referring to the *parameter in the model state*, and for that you refer to the XML object as a whole.

The above fix addresses this; see https://github.com/SED-ML/sed-ml/issues/75 for more discussion.

**Comment by jonrkarr** [comment]
I think it would be better for variables of data generators to be more specific. The above convention is ok kinetic SBML models, but isn't clear for other types of simulations where their are multiple predictions per model element.

At the very least, I suggest this be described as the convention for specific model languages, namely SBML (core) and CellML. This convention is similarly suitable for SBML-qual. LEMS/NeuroML is using a very different convention. SBML-fbc also needs a different convention.

**Comment by luciansmith** [comment]
Well, again, in SBML, the 'value' attribute of a Parameter means 'the initial value unless there's an InitialAssignment'.  It's perfectly fine to target this with a ComputeChange, but it won't do you any good if you're not a) at the beginning of the simulation and b) there's no InitialAssignment.  As such, all the examples in the spec are not only correct, but usually necessary.  They'd certainly be necessary in a DataGenerator, since presumably you'll usually want to read something out of the model besides the initial state.  Other languages are of course free to define things as they wish.

The only specification I'm familiar with of the counter-examples you list is SBML-fbc.  Can you describe what convention you would like for that?  Because again, even SBML-fbc attributes only define numerical values that apply at model initialization, and not beyond (unless they're constant).

**Comment by jonrkarr** [comment]
ComputeChange need not be tied to simulation at all. For models encoded in XML, this can be done solely on XML files. If the intension is that SED-ML+SBML can't be evaluated this way, I don't think this is clear. In general, the concept of emphemeral simulation state is not clear in the specifications of SED-ML.

What you're describing is a convention shared by SBML-core and CellML, rather than XML or XPaths. I think this is important to communicate that this is a convention for the combination of SED-ML with these languages, rather than something that is specifically part of SED-ML. This is important to note because it explains why this is isn't discussed in the SED-ML specifications (because its part of those languages, rather than SED-ML itself).

One example for SBML-FBC is flux variability analysis (FVA). For FVA, there are two predictions per reaction -- min and max flux. For the values of variables of data generators to be scalars, their target+symbol must be an XPath to a reaction defined in a model description and a symbol for min or max flux. This is a little different than the SBML-core and CellML convention where symbol=null means retrieve the canonical prediction of the associated simulation object, defined equal to amount/concentration by SBML-core and value by CellML. For SBML-FBC, there is no appropriate default (except to make the default an object with two properties, which could work except there isn't a great way to handle this with calculations, reports, and plots).
